[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
    '@prb/test/=node_modules/@prb/test/src/',
     'ds-test/=lib/ds-test/src/',
]
auto_detect_remappings = true
libraries = []
cache = true
cache_path = '.cache'
broadcast = 'broadcast'
allow_paths = []
include_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false

# compiler settings
build_info = false
verbosity = 2
via_ir = true
revert_strings = "verboseDebug"

optimizer = true
optimizer_runs = 1_337
# this may need to be uncommented if viaIR has issues
optimizerSteps = ''


verbosity = 0
# Ignored Error codes
# 2018 Function state mutability can be restricted to pure
# 3420 Source file does not specify required compiler version
# 3716 Multiple SPDX license identifiers found in source file
ignored_error_codes = [
  1878,
  2018,
  3420,
  3716,
]
deny_warnings = false
build_info = true

ffi = false
initial_balance = '0xffffffffffffffffffffffff'
sender = '0xafFEaFFEAFfeAfFEAffeaFfEAfFEaffeafFeAFfE'
tx_origin = '0xAaaaAaAAaaaAAaAAaAaaaaAAAAAaAaaaAaAaaAA0'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
block_prevrandao = '0x0000000000000000000000000000000000000000000000000000000000000000'
memory_limit = 33_554_432
extra_output = ['irOptimized', 'evm.assembly']
extra_output_files = ['metadata']
names = false
sizes = true

no_storage_caching = false
bytecode_hash = 'none'
cbor_metadata = false
sparse_mode = true

[[profile.default.fs_permissions]]
access = 'read'
path = 'out'

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
variable_override_spacing = true
wrap_comments = false
ignore = []

[profile.ci]
optimizer = false
fuzz_runs = 4_069
force = true
verbosity = 4

[fuzz]
runs = 256
max_test_rejects = 65536
max_global_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

